<a href="https://colab.research.google.com/github/buseacar/BuseTweet/blob/main/python_denemeler_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a='11'
print(a)
print(type(a))

11
<class 'str'>


In [ ]:
a=int(a)
print(a)
print(type(int(a)))

11
<class 'int'>


In [ ]:
b='x'
print(b)
print(type(b))

x
<class 'str'>


In [ ]:
b=int(b)  # bilinmeyen int olamaz hata verir

ValueError: invalid literal for int() with base 10: 'x'

In [ ]:
x=[14,25.5, 'yalova', ['ankara','london','paris','washington']]

In [ ]:
x

[14, 25.5, 'yalova', ['ankara', 'london', 'paris', 'washington']]

In [ ]:
x[-1][0:2]='istanbul','new york'  #0 dahil 2 değil yani 0 ve 1i değiştirdi.

In [ ]:
x

[14, 25.5, 'yalova', ['istanbul', 'new york', 'paris', 'washington']]

In [ ]:
x[-1][-1:3]='one','two','three','four'# (-) olunca sondaki -1 diğerleri yine de sağdan sayılıyor

In [ ]:
x

[14,
 25.5,
 'yalova',
 ['istanbul',
  'new york',
  'paris',
  'bir',
  'iki',
  'üç',
  'dört',
  'one',
  'two',
  'three',
  'four',
  'washington']]

In [ ]:
x[:]

[14,
 25.5,
 'yalova',
 ['istanbul',
  'new york',
  'paris',
  'bir',
  'iki',
  'üç',
  'dört',
  'one',
  'two',
  'three',
  'four',
  'one',
  'two',
  'three',
  'four',
  'washington']]

In [ ]:
x[1:] #1. eleman hariç

[25.5,
 'yalova',
 ['istanbul',
  'new york',
  'paris',
  'bir',
  'iki',
  'üç',
  'dört',
  'one',
  'two',
  'three',
  'four',
  'one',
  'two',
  'three',
  'four',
  'washington']]

In [ ]:
x[2,3] #sayıları sıralı seçebilir bunu yapamaz

In [ ]:
kisiler=['buse','barış','nehir','şevval']

In [ ]:
kisiler[2]='nehirr'
kisiler

['buse', 'barış', 'nehirr', 'şevval']

In [ ]:
kisiler.append('nursah') #listeye sonuncu ekler.

In [ ]:
kisiler

['buse', 'barış', 'nehirr', 'şevval', 'nursah']

In [ ]:
kisiler.insert(2,'gülşah') # (order,value) yani (emir verilen yer,değer)listede belirli sayıya kişi ekler ve kaydırır.
kisiler

NameError: name 'kisiler' is not defined

In [ ]:
ülkeler=['türkiye','almanya','fransa']

In [ ]:
ülkeler.pop(0) # 0'ı siliyor 1'i değil

'türkiye'

In [ ]:
ülkeler

['almanya', 'fransa']

In [ ]:
del ülkeler[-1] # listenin sonuncusunu siliyor

In [ ]:
ülkeler

[]

In [ ]:
del ülkeler #ülkeleri komple sildi

In [ ]:
ülkeler

NameError: name 'ülkeler' is not defined

In [ ]:
t=(5,2,'buse',1+3)  #turple(kaplumbağ) listeleri farklı type bulundurablir ama değiştirlemez ve eklenmez
t

(5, 2, 'buse', 4)

In [ ]:
b=dict(isim=['buse', 'barış'],age=[20,21])
print(b)   #bir değişken olarak saklanır (dict ve = kullanılır)

{'isim': ['buse', 'barış'], 'age': [20, 21]}


In [ ]:
c={'isim':['buse', 'barış'],'age':[20,21]}
print(c)  #bir karakter olarak saklanır (süslü parantez ve : kullanılır)

{'isim': ['buse', 'barış'], 'age': [20, 21]}


In [ ]:
hisse = {'Şirket Adı' : 'Apple Inc.','Hisse Kodu' : 'AAPL','Fiyat ($)'  : 163.91}
hisse

{'Şirket Adı': 'Apple Inc.', 'Hisse Kodu': 'AAPL', 'Fiyat ($)': 163.91}

In [ ]:
hisseler = [
    {'Şirket Adı': 'Apple Inc.', 'Hisse Kodu': 'AAPL', 'Fiyat ($)': 163.91},
    {'Şirket Adı': 'Microsoft',  'Hisse Kodu': 'MSFT', 'Fiyat ($)': 310.22},
    {'Şirket Adı': 'Google',     'Hisse Kodu': 'GOOGL','Fiyat ($)': 142.50}
]

In [ ]:
aranan_sirket=input("hangi şirketin fiyatını istiyorsunuz?")


hangi şirketin fiyatını istiyorsunuz?


In [ ]:
for hisse in hisseler:
    if hisse['Şirket Adı'].strip().lower()== aranan_sirket:  #strip boşluklara lower büyük küçük harfe takılmamasını sağlar.
        print(hisse)

In [ ]:
insanlar=[
    {'adı':'buse','yaş':20,'meslek':'öğrenci'},
    {'adı':'barış','yaş':21,'meslek':'öğrenci'},
    {'adı':'nehir','yaş':20,'meslek':'barmen'},
]

In [ ]:
for insan in insanlar:
    for k, v in insan.items():  #items ile k ve v ile oynayabiliriz
       if k =='meslek': #key=meslek kısmını
        insan[k]='öğrenci' # meslek=öğrenci yaptık hepsinde




In [ ]:
print(insanlar)

[{'adı': 'buse', 'yaş': 20, 'meslek': 'öğrenci'}, {'adı': 'barış', 'yaş': 21, 'meslek': 'öğrenci'}, {'adı': 'nehir', 'yaş': 20, 'meslek': 'öğrenci'}]


In [ ]:
insan.keys()  # keyleri listeler

dict_keys(['adı', 'yaş', 'meslek'])

In [ ]:
kediler={'adı':['buse','barış'],'yaş':[3,5]}
kediler

{'adı': ['buse', 'barış'], 'yaş': [3, 5]}

In [ ]:
kediler['adı']

['buse', 'barış']

In [ ]:
kediler['adı'][0]

'buse'

In [ ]:
hisseler_yeni= {"şirket adı": "Apple Inc.",
                "hisse kodu": "AAPL",
                "fiyat": 163.91 }
print(hisseler_yeni)


{'şirket adı': 'Apple Inc.', 'hisse kodu': 'AAPL', 'fiyat': 163.91}


In [ ]:
hisseler_yeni['şirket adı']

'Apple Inc.'

In [ ]:
hisseler_yeni['total şirket miktarı'] = 10 # kare parantez ile v,k ekleme

In [ ]:
hisseler_yeni.update({'sector':'teknoloji'}) # parantez ile v,k ekleme

In [ ]:
hisseler_yeni

{'şirket adı': 'Apple Inc.',
 'hisse kodu': 'AAPL',
 'fiyat': 163.91,
 'total şirket miktarı': 10,
 'sector': 'teknoloji'}

In [ ]:
hisseler_yeni.pop('total şirket miktarı') #istediğimiz v(value) yi çıkarttık

10

In [ ]:
hisseler_yeni

{'şirket adı': 'Apple Inc.',
 'hisse kodu': 'AAPL',
 'fiyat': 163.91,
 'sector': 'teknoloji'}

In [ ]:
x=10
y=15
print("x*y=",x*y)

x*y= 150


In [ ]:
print("x/y=",x/y)

x/y= 0.6666666666666666


In [ ]:
x=11
y=9
print(x>y)  # mantıksal işlemler true/false

True


In [ ]:
x=1
y=1.0
print(x==y)

True


In [ ]:
x=1.0
x=1.0
print(x!=y)

False


In [ ]:
numbers=range(1,12,1)  # 1 den 12 ye 1 er 1 er artış
numbers

range(1, 12)

In [ ]:
list(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
çift_sayılar=list(range(0,10,2))
çift_sayılar

[0, 2, 4, 6, 8]

In [ ]:
liste=[]
tek_sayilar_listesi=[]
sayac1=0
sayac2=0

for i in range(1,10+1):
  sayi=input("bir sayı giriniz")

  if sayi.strip() == "":
        print("yanlış tuşlama")
        continue
  sayi=int(sayi)
  liste.append(sayi)
  sayac1 += 1
  print(sayac1)

for sayi in liste:
  if sayi%2==1:
    tek_sayilar_listesi.append(sayi)
    sayac2+=1
print("tek sayılar:", tek_sayilar_listesi)

bir sayı giriniz1
1
bir sayı giriniz2
2
bir sayı giriniz3
3
bir sayı giriniz4
4
bir sayı giriniz
yanlış tuşlama
bir sayı giriniz5
5
bir sayı giriniz6
6
bir sayı giriniz7
7
bir sayı giriniz8
8
bir sayı giriniz9
9
tek sayılar: [1, 3, 5, 7, 9]


In [ ]:
liste = []  #bu da aynısının yanlış tuşlamayı sayaca katmadığı wheel versiyonu
sayac = 0

while sayac < 10:
    sayi = input("bir sayı giriniz: ")

    if sayi.strip() == "":
        print("yanlış tuşlama, tekrar dene")
        continue

    try:
        sayi = int(sayi)
    except ValueError:
        print("sayı girmen lazım")
        continue

    liste.append(sayi)
    sayac += 1
    print("girilen doğru sayı:", sayac)


bir sayı giriniz: 1
girilen doğru sayı: 1
bir sayı giriniz: 2
girilen doğru sayı: 2
bir sayı giriniz: 3
girilen doğru sayı: 3
bir sayı giriniz: 4
girilen doğru sayı: 4
bir sayı giriniz: 5
girilen doğru sayı: 5
bir sayı giriniz: 6
girilen doğru sayı: 6
bir sayı giriniz: 7
girilen doğru sayı: 7
bir sayı giriniz: 8
girilen doğru sayı: 8
bir sayı giriniz: 9
girilen doğru sayı: 9
bir sayı giriniz: 
yanlış tuşlama, tekrar dene
bir sayı giriniz: 10
girilen doğru sayı: 10


In [2]:
import numpy as np # numpyi kısaltıyorum demek np olarak

In [3]:
np.zeros(5) # daha ileri matematik için numpy kullanılıoyr.

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((2,3),dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.ones((3,4),dtype=float) #dtype=datatype  #array düzenli demek

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
düzenli = np.array([1, 2, 3, 4])

In [11]:
print(duzenli)


[1 2 3 4]


In [12]:
liste = [1, 2, 3, 4]
liste * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
arr = np.array([1, 2, 3, 4])
arr * 2   #farkı

array([2, 4, 6, 8])